services:
  todo-db:
    image: diamol/postgres:11.5
    # 조건 1
    restart: unless-stopped
    environment:
      - PGDATA=/var/lib/postgresql/data
    # 조건 2
    volumes:
      - type: bind
        source: ./postgresql/data
        target: /var/lib/postgresql/data
    networks:
      - app-net

  todo-web:
    image: diamol/ch06-todo-list
    # 조건 1
    restart: unless-stopped
    # 조건 3
    ports:
      - "8050:80"
    environment:
      - Database:Provider=Postgres
    depends_on:
      - todo-db
    secrets:
      - source: postgres-connection
        target: /app/config/secrets.json
secrets:
  postgres-connection:
    file: ./postgres-connection.json
networks:
  app-net:
    external:
      name: nat
